export const GETTING_PLAYERS = 'GETTING_PLAYERS';
export const GETTING_PLAYERS_SUCCESS = 'GETTING_PLAYERS_SUCCESS';
export const GETTING_PLAYERS_FAILURE = 'GETTING_PLAYERS_SUCCESS';

export const ADDING_PLAYER = 'ADDING_PLAYER';
export const ADDING_PLAYER_SUCCESS = 'ADDING_PLAYER_SUCCESS';
export const ADDING_PLAYER_FAILURE = 'ADDING_PLAYER_FAILURE';
